ehcache.configuration: ${CONFIG_FILE}

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t [%A:%p] [%h] [%I] %l %u "%r" %s %b %D'
      directory: /logs
      prefix: legacycache_access_log
      suffix: .log
  servlet:
    context-path: ${CONTEXT_ROOT}
  port: ${PORT}

spring:
  application:
    name: legacycache
  profiles:
    active: ${PROFILE}
  resources:
    chain:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"